version: '3.8'

services:
  rails-cucumber:
    build:
      context: ./
      dockerfile: Dockerfile.test
    container_name: rails-cucumber-testing
    stdin_open: true
    tty: true
    volumes:
      - './:/usr/src/myapp'
  rails-rottenpotatoes:
    build:
      context: ./
      dockerfile: Dockerfile.web
    container_name: rails-rottenpotatoes-web
    ports:
      - 3000:3000
